#!/usr/bin/env bash
# Foundry — protect tool-generated baselines from hand-edits (PreToolUse).
# snooze.json / eslint-suppressions.json are REGENERATED by tools (bootstrap prune,
# eslint --prune-suppressions), never edited by hand: a manual edit is fragile
# (whole-file snooze granularity) and usually wrong, and it's how agents break CI.
# Covers the agent's Edit/Write/MultiEdit AND *mutating* Bash (redirects, sed -i,
# tee, cp/mv) so it can't be touched through any tool. Reads pass. CI/bootstrap
# regenerate these outside the agent's tools; a human editing directly isn't affected.
set -u

payload=$(cat)
tool=$(printf '%s' "$payload" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)

deny_snooze() {
  {
    echo "Refusing to touch snooze.json — it is a tool-generated baseline, not hand-edited."
    echo "It's whole-file granular, so a hand edit that leaves a still-smelly file just fails"
    echo "the smells job. To SHRINK it: fully clear a file's findings, then regenerate via the"
    echo "bootstrap workflow (habit-sensors --all | habit-snooze --prune) — which only shrinks."
    echo "Never grow it. See the repo-align skill."
  } >&2
  exit 2
}
deny_eslint() {
  {
    echo "Refusing to touch eslint-suppressions.json — it is a tool-generated baseline."
    echo "Shrink it with 'mise run fix' (eslint --prune-suppressions), never by hand."
    echo "Never grow it to make lint pass. See the repo-align skill / CONTRACT.md."
  } >&2
  exit 2
}

case "$tool" in
  Bash)
    # Block only a command that WRITES a protected baseline — the file must be the
    # target of a redirect / sed -i / tee / cp|mv|install. Adjacency matters: merely
    # naming the file (a read, or a commit message that mentions it) must pass, so we
    # don't match "token somewhere + filename somewhere". Reads (cat/grep/git show/jq).
    writes() { # $1 = filename, dot escaped
      printf '%s' "$payload" | grep -Eq ">>?[[:space:]]*['\"]?[^ '\";|&<>()]*$1|[[:space:]\"'](tee|cp|mv|install|rsync)[[:space:]]+[^|;&]*$1|sed[[:space:]]+[^|;&]*-i[^|;&]*$1|--in-place[^|;&]*$1|of=[^ ]*$1"
    }
    writes 'snooze\.json'              && deny_snooze
    writes 'eslint-suppressions\.json' && deny_eslint
    exit 0 ;;
  *)
    file=$(printf '%s' "$payload" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1 | sed 's/\\\\/\\/g')
    [ -n "$file" ] || exit 0
    case "$file" in
      *snooze.json) deny_snooze ;;
      *eslint-suppressions.json) deny_eslint ;;
    esac
    exit 0 ;;
esac
