#!/usr/bin/env bash
# Foundry — block hand-edits to tool-generated baselines (PreToolUse: Edit|Write|
# MultiEdit). snooze.json and eslint-suppressions.json are REGENERATED by tools,
# never edited by hand: a manual edit is fragile (whole-file snooze granularity)
# and usually wrong, and it's how agents keep breaking CI. Enforcement beats the
# recall of a skill doc. exit 2 blocks the tool call and tells the agent the path.
#
# Fires only on the agent's own Edit/Write — CI/bootstrap regenerate these outside
# the agent's tools, and a human editing directly isn't affected.
set -u

payload=$(cat)
file=$(printf '%s' "$payload" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1 | sed 's/\\\\/\\/g')
[ -n "$file" ] || exit 0

case "$file" in
  *snooze.json)
    {
      echo "Refusing to hand-edit snooze.json — it is a tool-generated baseline."
      echo "It's whole-file granular, so a hand edit that removes a still-smelly file"
      echo "just fails the smells job. To SHRINK it: fully clear a file's findings, then"
      echo "regenerate via the bootstrap workflow (habit-sensors --all | habit-snooze"
      echo "--prune) — which can only shrink. Never grow it. See the repo-align skill."
    } >&2
    exit 2 ;;
  *eslint-suppressions.json)
    {
      echo "Refusing to hand-edit eslint-suppressions.json — it is a tool-generated baseline."
      echo "Shrink it with 'mise run fix' (eslint --prune-suppressions), never by hand."
      echo "Never grow it to make lint pass. See the repo-align skill / CONTRACT.md."
    } >&2
    exit 2 ;;
esac
exit 0
